development:
 adapter: postgresql
 encoding: unicode
 database: roll_dev
 host: localhost
 pool: 5
 username: onyx
 password: password

staging:
 adapter: postgresql
 encoding: unicode
 database: roll_staging

production:
 adapter: postgresql
 encoding: unicode
 database: roll_production